# This is an example to show that configuration file can be added to a single file
# To deploy container to Kubernetes, we need to create a separate Config files to all the Service
# Or we can create a single config file and all the configuration to it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: mtandur/multi-server
          ports:
            - containerport: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000